accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'
urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup'),
]

blog/urls.py
from django.urls import path

from . import views

app_name= 'blog'

urlpatterns = [
    path('', views.PostListView.as_view(), name='post_list'),
    path('<int:pk>/', views.PostDetailView.as_view(), name='post_detail'),
    path('<int:pk>/update/', views.PostUpdateView.as_view(), name='post_update'),
    path('<int:pk>/delete/', views.PostDeleteView.as_view(), name='post_delete'),
    path('add/', views.PostCreateView.as_view(), name='post_add'),
    path('<int:pk>/comment/', views.CommentCreateView.as_view(), name='comment_create'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('', include('blog.urls')),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class CustomUser(AbstractUser):
    pass

blog/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.urls import reverse

class Post(models.Model):
    title = models.CharField(max_length=50)
    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    text = models.TextField()

    datetime_created = models.DateTimeField(auto_now_add=True)
    datetime_modified = models.DateTimeField(auto_now=True)
    
    status = models.BooleanField(default=True)

    def __str__(self):
        return f'{self.author}: {self.title}'
    
    def get_absolute_url(self):
        return reverse('blog:post_detail', args={self.pk})

class CommentPost(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    text = models.TextField()

    datetime_created = models.DateTimeField(auto_now_add=True)
    datetime_modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.text
    

accounts/forms.py
from django.contrib.auth.forms import UserChangeForm, UserCreationForm

from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ['email', 'username',]

class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = ['email', 'username',]

blog/forms.py
from django import forms
from .models import CommentPost

class CommentForm(forms.ModelForm):
    class Meta:
        model = CommentPost
        fields = ('text',)

accounts/views.py
from django.shortcuts import render
from django.views import generic
from django.urls import reverse_lazy

from .forms import CustomUserCreationForm


class SignUpView(generic.CreateView):
    form_class = CustomUserCreationForm
    template_name = 'registration/signup.html'
    context_object_name = 'form'
    success_url = reverse_lazy('login')

blog/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.forms.models import BaseModelForm
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.views import generic
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin


from .models import Post , CommentPost
from .forms import CommentForm

class PostListView(generic.ListView):
    model= Post
    template_name ='blog/post_list.html'
    context_object_name= 'posts'

    def get_queryset(self):
        return Post.objects.filter(status= True)
    
class PostDetailView(generic.DetailView):
    model = Post
    template_name = 'blog/post_detail.html'
    context_object_name= 'post'     


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comment_form'] = CommentForm()
        context['comments'] = CommentPost.objects.filter(post=self.object)
        return context
    
    def post(self, request, *args, **kwargs):
        post = self.get_object()
        form = CommentForm(request.POST)
        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.post = post
            new_comment.user = request.user 
            new_comment.save()
            return redirect(post.get_absolute_url())
        return self.get(request, *args, **kwargs)

class CommentCreateView(generic.CreateView):
    model = CommentPost
    form_class = CommentForm
    template_name = 'blog/post_detail.html'

    def form_valid(self, form):
        form.instance.post_id = self.kwargs['pk']
        form.instance.user_id = self.request.user.id
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('blog:post_detail', kwargs={'pk': self.kwargs['pk']})

class PostUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Post
    template_name= 'blog/post_update.html'
    fields = ('title', 'text', 'status',)
    success_url = reverse_lazy('blog:post_list')

class PostDeleteView(LoginRequiredMixin, generic.DeleteView):
    model= Post
    template_name= 'blog/post_delete.html'
    success_url = reverse_lazy('blog:post_list')

class PostCreateView(LoginRequiredMixin, generic.CreateView):
    model= Post
    template_name= 'blog/post_create.html'
    fields = ('title', 'text', 'status', 'author',)

blog/templates/blog/post_create.html
{% extends "_base.html" %}

{% load crispy_forms_tags %}

{% block page_title %}Update{% endblock page_title %}

{% block content %}
    <div class="container mt-4">
        <div class="row">
            <div class="col-9">
                    <div class="card shadow-sm my-3">
                            <form class="card-body" method="post" action="{{posts.get_absolute_url}}">
                                {% csrf_token %}
                                {{form|crispy}}
                                <input class="btn btn-sm btn-warning" type="submit" value="Create">
                            </form>
                    </div>
                </div>
        </div>
    </div>
{% endblock content %}

blog/templates/blog/post_delete.html
{% extends "_base.html" %}


{% block page_title %}Update{% endblock page_title %}

{% block content %}
    <div class="container mt-4">
        <div class="row">
            <div class="col-9">
                    <div class="card shadow-sm my-3">
                            <form class="card-body" method="post" action="{{posts.get_absolute_url}}">
                                {% csrf_token %}
                                <h3>Are you sure you want to delete this post {{post.title}}</h3>
                                <input class="btn btn-sm btn-danger" type="submit" value="Yes">
                            </form>
                    </div>
                </div>
        </div>
    </div>
{% endblock content %}

blog/templates/blog/post_detail.html
{% extends "_base.html" %}
{% load crispy_forms_tags %}
{% block page_title %}Post Detail{% endblock page_title %}

{% block content %}
    <div class="container mt-4">
        <div class="row">
            <div class="col-9">
                    <div class="card shadow my-3 p-5">
                        <h1>{{post.title}}</h1>
                        <p class="small text-muted mt-2">By: {{post.author}}</p>
                        <p class="mt-2">{{post.text}}</p>
                        <a href="{% url "blog:post_update" post.id%}"
                            class="btn btn-sm btn-warning">
                                Edit
                            </a>
                        <a href="{% url "blog:post_delete" post.id %}"
                        class="btn btn-sm btn-danger">
                            Delete
                        </a>
                    </div>
                    {% for comment in comments %}
                        <div class="card shadow my-3 p-5">
                            <h3>Comments:</h3>
                                <p class="small text-muted mt-2">By: {{comment.user}}</p>
                                <p class="small text-muted mt-2">Date: {{comment.datetime_modified}}</p>
                                {{comment.text}}
                        </div>
                    {% endfor %}
                
                    <div class="card shadow my-3 p-5">
                        <h3>Add new comment:</h3>
                        <form method="POST" action="{% url 'blog:comment_create' post.id %}">
                            {% csrf_token %}
                            {{ comment_form|crispy }}
                            {% comment %} <div class="form-group py-2">
                                <label class="py-1" for="author_name">Enter your name:</label>
                                <input type="text" class="form-control" placeholder="e.g. John Doe" name="author_name">
                            </div>
                            <div class="form-group py-2">
                                <label class="py-1" for="email">Your Email:</label>
                                <input type="email" class="form-control" placeholder="example@gmail.com" name="email">
                            </div>
                            <div class="form-group py-2">
                                <label class="py-1" for="comment_text">Comment text:</label>
                                <textarea class="form-control" name="text" rows="3" placeholder="Enter your comment text here..."></textarea>
                            </div> {% endcomment %}
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </form>
                    </div>
            </div>
            <div class="col-3">
                    <div class="card my-4">
                        <h5 class="card-header">About</h5>
                        <div class="card-body">
                            <p class="card-text">We love python and django. So we created a blog site to share our
                                thoughts</p>
                            <a href="#"
                            class="btn btn-sm btn-danger">
                                More...
                            </a>
                        </div>
                    </div>
            </div>
        </div>
    </div>

{% endblock content %}

blog/templates/blog/post_list.html
{% extends "_base.html" %}

{% block page_title %}Post List{% endblock page_title %}

{% block content %}
    <div class="container mt-4">
        <div class="row">
            <div class="col-9">
                {% for post in posts %}
                    <div class="card shadow-sm my-3">
                            <div class="card-body">
                                <h5 class="card-title">{{post.title}}</h5>
                                <h6 class="card-subtitle mb-2 text-muted small py-2">{{post.datetime_modified}}</h6>
                                <p class="card-text py-3">
                                    {{post.text}}
                                </p>
                                <a class="btn btn-sm btn-success" href="{{post.get_absolute_url}}"  >Read More</a>
                            </div>
                    </div>
                {% endfor %}
                </div>
            <div class="col-3">
                    <div class="card my-4">
                        <h5 class="card-header">About</h5>
                        <div class="card-body">
                            <p class="card-text">We love python and django. So we created a blog site to share our
                                thoughts</p>
                            <a href="#"
                            class="btn btn-sm btn-danger">
                                More...
                            </a>
                        </div>
                    </div>
            </div>
        </div>
    </div>
{% endblock content %}

blog/templates/blog/post_update.html
{% extends "_base.html" %}

{% load crispy_forms_tags %}

{% block page_title %}Update{% endblock page_title %}

{% block content %}
    <div class="container mt-4">
        <div class="row">
            <div class="col-9">
                    <div class="card shadow-sm my-3">
                            <form class="card-body" method="post" action="{{posts.get_absolute_url}}">
                                {% csrf_token %}
                                {{form|crispy}}
                                <input class="btn btn-sm btn-warning" type="submit" value="Update">
                            </form>
                    </div>
                </div>
        </div>
    </div>
{% endblock content %}

templates/_base.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <link rel="stylesheet" href="css/style.css">
    <link rel="stylesheet" href="css/login.css">

    <title>{% block page_title %}{% endblock page_title %}</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Barbodj</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
                    aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <a class="nav-link active" aria-current="page" href="{% url "blog:post_list" %}">Home</a>
                    {% if user.is_authenticated %}
                        <a class="nav-link" href="{% url "blog:post_add" %}">Blog</a>
                    {% endif %}
                </div>
            </div>
            {% if user.is_authenticated %}
            <div class="mx-2 text-white">Welcome {{user.username}}</div>
            <form method="post" action="{%url 'logout'%}">
                {% csrf_token %}
                <input class="btn btn-danger" value="Logout" type="submit">
            </form>
        </div>
            {% else %}
                <a class="btn btn-success" href={% url "accounts:signup" %}>SignUp</a>
                <a class="btn btn-light" href={% url "login" %}>Login</a> 
            {% endif %}
    </nav>
    
    <div class="container-fluid bg-info">
        <div class="row py-3">
            <div class="col-md-8 col-md-10 mx-auto">
                <h3 class="my-4 mt-3 text-white">Welcome to Python and Django Blog</h3>
                <p class="text-light">We share python and django tips and tricks here</p>
            </div>
        </div>
    </div>    
    {% block content %}
    
    {% endblock content %}
    
        <!-- jQuery first, then Bootstrap JS. -->
    <script src="./js/jquery.min.js"></script>
    <script src="./js/bootstrap.min.js" crossorigin="anonymous"></script>
    
</body>
</html>